### ISSUE TITLE
Feat: Please provide usable css

### ISSUE THREAD

**Issue by guettli** [NickDJM/accessible-menu#79]
I found some css here:

https://github.com/NickDJM/accessible-menu/blob/dev/test/css/styles.css

It would be very kind if you could provide css which works for basic usage and which does not include css for other things (like html font-family).

**Comment by NickDJM** [comment]
The tests aren't intended to be used as examples. They are purely for making sure the menu is functioning as intended when adding/editing features. Any stylistic choices made in them were just me having some fun while testing the menu functionality.

To be honest, when I have some time to write some automated tests those css files most likely will not exist at all.

I currently have no plans in providing "official" css with this project. The examples in jsfiddle are probably the closes I will get there.

**Comment by guettli** [comment]
No official css? Why?

**Comment by NickDJM** [comment]
On any given day, I work with various "themes": basic Drupal Bartik/Seven/Stark menus, Bootstrap 3 & 4, Tailwind, and custom CSS. They all handle menu styling in their own way.

I wanted this project to hook into any existing theme and ensure aria-labels are correctly placed and key/click events are handled. Styling is up to the user. The openClass/closeClass values are there so you don't need to write CSS based on the `aria-expanded` prop, since some people consider that bad-practice.

I'd rather let designers decide how they want their menus to look, and just plug this in to help with the functional side of things.
